version: '3.9'

services:
  db:
    container_name: postgres-dev
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: test_db
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: