version: '3'

services:
  db:
    container_name: pg-gis-docker
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: gis_db_user
      POSTGRES_PASSWORD: sr7%f/+=bXjvRoQ
      POSTGRES_DB: gis_db
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    container_name: spring-gis-docker
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gis_db
      SPRING_DATASOURCE_USERNAME: gis_db_user
      SPRING_DATASOURCE_PASSWORD: sr7%f/+=bXjvRoQ
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /var/log/gis-api:/var/log/gis-api

volumes:
  db-data: