version: '3'

services:
  db:
    container_name: pg-gis-docker
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: gis_db
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    container_name: spring-gis-docker
    image: registry.gitlab.com/hard2code/gis-api:1.0.2
    ports:
      - "9090:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gis_db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - app-logs:/var/log/gis-api

volumes:
  app-logs:
  db-data:
