spring:
  main:
    banner-mode: off

  profiles:
    active: dev

  jpa:
    open-in-view: false

spring-doc:
  swagger-ui:
    path: /api/swagger-ui

server:
  error:
    include-stacktrace: never
    whitelabel.enabled: false

app:
  name: Government Information Systems Rest API
  url: https://api.gis.hard2code.ru

  rest:
    api-prefix: /api/v1
