spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/test_db
    username: usr
    password: pwd

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  sql:
    init:
      platform: postgres
      mode: always

app:
  rest:
    basic-auth:
      user:
        name: usr
        password: pwd

      admin:
        name: admin
        password: pwd