spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5430/gis_db
    username: gis_db_user
    password: skibidiwapapa

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update