spring:
  main:
    banner-mode: off

  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5430/gis_db
    username: gis_db_user
    password: skibidiwapapa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

spring-doc:
  swagger-ui:
    path: /swagger-ui

server:
  servlet.context-path: /api