spring:
  main:
    banner-mode: off

  profiles:
    active: dev

  web:
    resources:
      add-mappings: false


spring-doc:
  swagger-ui:
    path: /api/swagger-ui
    disable-swagger-default-url: true


server:
  error:
    include-stacktrace: never
    whitelabel.enabled: false

app:
  rest:
    api-prefix: /api/v1
