spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/test_db
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      enable-lazy-load-no-trans: false

  sql:
    init:
      platform: postgres
      mode: always

app:
  rest:
    auth:
      user:
        name: usr
        password: pwd

      admin:
        name: admin
        password: pwd
