spring:
  main:
    banner-mode: off

  profiles:
    active: dev

spring-doc:
  swagger-ui:
    path: /api/swagger-ui

server:
  error:
    include-stacktrace: never
    whitelabel.enabled: false

app:
  name: Government Information Systems Rest API
  rest:
    api-prefix: /api/v1
