
CREATE TABLE information_systems
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_information_systems PRIMARY KEY (id)
);

CREATE TABLE organizations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    address       VARCHAR(255),
    is_government BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

CREATE TABLE questions
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label                 VARCHAR(255)                            NOT NULL,
    answer                VARCHAR(32600)                          NOT NULL,
    information_system_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id      VARCHAR(10)                             NOT NULL,
    email        VARCHAR(50)                             NOT NULL,
    phone        VARCHAR(12),
    username     VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    user_role_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_information_systems_name UNIQUE (name);

ALTER TABLE organizations
    ADD CONSTRAINT uc_organizations_name UNIQUE (name);

ALTER TABLE user_roles
    ADD CONSTRAINT uc_user_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_chat UNIQUE (chat_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE questions
    ADD CONSTRAINT FK_QUESTIONS_ON_INFORMATION_SYSTEM FOREIGN KEY (information_system_id) REFERENCES categories (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_USER_ROLE FOREIGN KEY (user_role_id) REFERENCES user_roles (id);
