name: Deploy on production

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.12.0
        with:
          java-version: ${JAVA_VERSION}
          distribution: liberica
          cache: 'gradle'

      - name: Setup Java JDK
        run: |
          ./gradlew test
          ./gradlew jib
