name: Deploy on production

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.12.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: liberica
          cache: 'gradle'



      - name: Run tests
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Build image and pull to docker registry
        run: ./gradlew jib
